# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

---
version: 2
registries:
  github:
    type: git
    url: https://github.com
    username: x-access-token
    password: ${{ secrets.SYS_ORCH_GITHUB }}
updates:
  - package-ecosystem: "gomod"
    directories:
      - "/"
    registries:
      - github
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    commit-message:
      prefix: "[gomod] "
  - package-ecosystem: "github-actions"
    directory: "/"
    registries:
      - github
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    commit-message:
      prefix: "[gha] "
  - package-ecosystem: "docker"
    directories:
      - "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    commit-message:
      prefix: "[docker] "
