# SPDX-FileCopyrightText: (C) 2026 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

apiVersion: v2
name: observability-tenant-controller
description: A Helm chart for Observability Tenant Controller
type: application
version: 0.7.5
appVersion: 0.7.5
annotations:
  revision: b5b1ecbd69be365555a990457b20924f3aa074b1
  created: "2026-05-15T05:54:10Z"
