# SPDX-FileCopyrightText: (C) 2026 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

apiVersion: v2
name: observability-tenant-controller
description: A Helm chart for Observability Tenant Controller
type: application
version: 0.7.6
appVersion: 0.7.6
annotations:
  revision: 1dbdf31b2a03afc4c7fdd1c5deb0f85882eed6ff
  created: "2026-05-25T12:07:01Z"
