# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "observability-tenant-controller.fullname" . }}
  labels:
    {{- include "observability-tenant-controller.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "observability-tenant-controller.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "observability-tenant-controller.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: observability-tenant-controller
          image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ include "observability-tenant-controller.ports.prometheus" . }}
            - containerPort: {{ include "observability-tenant-controller.ports.grpc" . }}
          args:
            - "--config={{ .Values.configmap.mountPath }}/config.yaml"
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 500m
              memory: 256Mi
          volumeMounts:
            - name: config
              mountPath: {{ .Values.configmap.mountPath }}
              readOnly: true
          securityContext:
            capabilities:
              drop:
                - ALL
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        seccompProfile:
          type: RuntimeDefault
      serviceAccountName: observability-tenant-controller
      volumes:
        - name: config
          configMap:
            name: "observability-tenant-controller-config"
            items:
              - key: config.yaml
                path: config.yaml
