# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: observability-tenant-controller
rules:
  - apiGroups:
      - "runtimeproject.edge-orchestrator.intel.com"
      - "projectactivewatcher.edge-orchestrator.intel.com"
      - "projectwatcher.edge-orchestrator.intel.com"
      - "runtimefolder.edge-orchestrator.intel.com"
      - "runtimeorg.edge-orchestrator.intel.com"
      - "runtime.edge-orchestrator.intel.com"
      - "tenancy.edge-orchestrator.intel.com"
      - "config.edge-orchestrator.intel.com"
    resources:
      - runtimeprojects
      - projectactivewatchers
      - projectwatchers
      - runtimefolders
      - runtimeorgs
      - runtimes
      - multitenancies
      - configs
    verbs: [ "*" ]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: observability-tenant-controller
subjects:
  - kind: ServiceAccount
    name: observability-tenant-controller
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: observability-tenant-controller
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: observability-tenant-controller
  namespace: {{ .Release.Namespace }}
